### ISSUE TITLE
[Feat] QuizView 구성하기

### ISSUE THREAD

**Issue by hotsunnyday** [DeveloperAcademy-POSTECH/MC3-Team14-FindAnimalFriends#15]
## Description
Quiz의 내용과 버튼을 보여주는 View를 구성하고 세부 동작을 구현합니다.

## To-do
- [x] 페이지 기본 요소 삽입 (버튼, 텍스트 등)
- [x] 책을 넘기는 듯한 화면 전환 구현
- [x] 답과 질문에 따른 버튼 액션 구현
