### ISSUE TITLE
[Feat] EntranceView - 퀴브 뷰로 진입하는 확대 뷰 구성하기

### ISSUE THREAD

**Issue by BrightHyeon** [DeveloperAcademy-POSTECH/MC3-Team14-FindAnimalFriends#32]
## Description
- 해당 동물의 퀴즈 VC로 넘어가기 전의 입구 뷰이다. (확대된 상태)

## To-do
- [ ] [Feat] Zoom Out 하는 cancel button 구성하기
- [ ] [Feat] QuizVC로 넘어가는 push button 구성하기
- [ ] [Feat] QuizVC에 알맞은 데이터 넘기는 흐름 구성하기
