### ISSUE TITLE
[Feat] QuizViewController에 버튼 추가

### ISSUE THREAD

**Issue by hotsunnyday** [DeveloperAcademy-POSTECH/MC3-Team14-FindAnimalFriends#40]
## Description
현재 QuizPageViewController에 버튼이 따로 빠져있습니다. QuizViewController에 버튼을 추가할 예정입니다.

## To-do
- [x] QuizViewController에 버튼 추가
- [x] QuizPageViewController에 버튼 제거
- [x] 버튼 기능 작동 확인
