### ISSUE TITLE
[Feat] EntranceView 구성

### ISSUE THREAD

**Issue by BrightHyeon** [DeveloperAcademy-POSTECH/MC3-Team14-FindAnimalFriends#47]
## Description
- MainVC -> QuizVC로 가는 EntranceView 구성

## To-do
- [x] Push Button 색감 및 디자인 입히기
- [x] 간단 설명 TextView 추가하기
- [x] Data 혹은 AnimalName 넘기기
