### ISSUE TITLE
[Add] QuizExplanationView 구성하기

### ISSUE THREAD

**Issue by Byeongsoo-Min** [DeveloperAcademy-POSTECH/MC3-Team14-FindAnimalFriends#76]
## Description
퀴즈를 풀고, 정답을 맞췄을 때 발생하는 이벤트로 퀴즈에 대한 설명 뷰를 띄우려고 합니다. 기본적인 틀은 QuizWrongView를 가져가되, 그 안에서 세세한 변경점은 바꿀 생각입니다~!

## To-do
- [ ] QuizWrongView 해석하기
- [ ] QuizExplanationView, ViewController 생성하기
- [ ] 퀴즈뷰에서 던진 데이터 받아서 연결하기
- [ ] 자잘한 UI 수정하기
