### ISSUE TITLE
[Feat] MainVC - Quiz Contents Retry

### ISSUE THREAD

**Issue by BrightHyeon** [DeveloperAcademy-POSTECH/MC3-Team14-FindAnimalFriends#78]
## Description
- 풀었던 문제도 다시 들어갈 수 있도록 로직 점검

## To-do
- [x] 풀었던 문제는 클리어해도 로티재생 안되도록 하기
- [x] 풀었던 문제의 경우 EntranceView의 button title이 "다시 풀기"가 되도록 하기
- [x] 새로운 문제를 풀었을 때만 openIndex update 하기 & Lottie 재생
